spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?serverTimezone=UTC
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  messages:
    encoding: utf-8
    basename: message_zh_CN